### PR TITLE
fix: 🐛 calculation formula fixed, also made code a little fnAL

### LINKED ISSUE #6: Fix Reward calculation
https://github.com/buidl-labs/yieldscan-frontend/blob/59fe3715e353d330354967c9c091065f72e254ac/lib/calculate-reward.js#L24

the above formula should be: 
```
Math.max(v.estimatedPoolReward - (v.commission / 100 * v.estimatedPoolReward) , 0) * stakeFraction
```

### PR DESCRIPTION
**Pull request by akshatbhargava123**
- closes #6 and #7

### CODE REVIEW

File: lib/calculate-reward.js [hunk 1]
```diff
@@ -18,13 +18,12 @@ const calculateReward = async (validators = [], amount, timePeriodValue, timePer
 	// 21900 = number of eras in 15 years (365 * 4 * 15)
 	if (timePeriodInEras > 21900) throw new Error('15 years are enough to make you rich, please adjust the time period.');
 
-	let totalReward = 0;
-	validators.forEach(v => {
+	const totalReward = validators.reduce((tr, v) => {
 		const stakeFraction = amountPerValidator / (amountPerValidator + v.totalStake);
-		const reward = Math.max(v.estimatedPoolReward - v.commission, 0) * stakeFraction;
+		const reward = Math.max(v.estimatedPoolReward - (v.commission / 100 * v.estimatedPoolReward) , 0) * stakeFraction;
```
Comment (saumyakaran) [inline lib/calculate-reward.js:23]: @akshatbhargava123 Why do we even proceed forward if we're getting a negative value for `v.estimatedPoolReward - (v.commission / 100 * v.estimatedPoolReward)? The output will always be incorrect in such a scenario, and in such a case there's clearly a mistake on our part - i.e. the user shouldn't receive wrong info.

Comment (akshatbhargava123) [reply lib/calculate-reward.js:23]: discussed, will remove it now.
